languageCode = "en"
languageName = "English"
weight = 1
title = "sastroza.cl"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Sebastián Astroza Tagle"
  image = "img/avatar2.jpg"
   #image = "img/blowfish_logo.png"
  headline = "Researcher | Associate Professor | Cinephile"
   bio = "I’m an Associate Professor at the Industrial Engineering Department at Universidad de Concepción in Concepción, Chile. My research line is Choice Modeling applied to transportation demand, travel behavior, time-use and activities, and sustainable mobility. I teach Discrete Choice Models, Systems Modeling, Simulation, Stochastic Processes, and Advanced Econometrics at the Civil Industrial Engineering undergrad, master, and PhD programs."
links = [
 { email = "mailto:sastroza@udec.cl" },
{ link = "https://www.webofscience.com/wos/author/record/3881761" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
{ google = "https://scholar.google.com/citations?user=NeThwLMAAAAJ&hl=en" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
{ twitter = "https://twitter.com/SecuAstroza" },
#     { whatsapp = "https://wa.me/phone-number" },
     { youtube = "https://www.youtube.com/channel/UC3F_tMNzpfY5f9-6-xvek0A" },
#     { ko-fi = "https://ko-fi.com/username" },
]
